### ISSUE TITLE
undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by katawura** [codeschool/FeatureFocus#2]
l keep getting an Error saying "undefined method `id' for nil:NilClass". and the extract the source below:

scope :all_for, ->(user){
joins(:accesses).where(accesses: { user_id: user.id })
}

end

Any idea how l can fix this please?

And was devise used on this course?

**Comment by conradwt** [comment]
Hi, there's no need to specify accesses as the key within the where clause.  Thus, you should be able to do the following:

``` ruby
scope :all_for, ->(user){
joins(:accesses).where(user_id: user.id) }
```

**Comment by katawura** [comment]
I still get the same error

**Comment by katawura** [comment]
Thanks for the comment but I still get the same error with your code

**Comment by conradwt** [comment]
@katawura Your user instance is nil.  Please recheck that you're passing a non-nil user instance to the scope and you should be able to verify things within the rails console.
